### Phonebook api testing client

GET http://localhost:3001/api/persons
Accept: application/json

###

GET http://localhost:3001/api/info
Accept: text/html

###

GET http://localhost:3001/api/persons/2
Accept: application/json

###

DELETE http://localhost:3001/api/persons/2

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Big Bad Bob",
  "number": "04859290339"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "04859290339"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "number": "04859290339"
}